# Generated by Django 3.1.2 on 2021-04-25 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close', models.BooleanField(default=False, verbose_name='Recebida')),
                ('kind', models.CharField(choices=[('REVENUE', 'Receita'), ('EXPENSE', 'Despesa')], max_length=10, verbose_name='Natureza')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Data Recebiento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_moves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentação',
            },
        ),
    ]
